make:
	gcc -Wall -ansi -o echo_client echo_client.c
	gcc -Wall -ansi -lpthread -o p_echo_server p_echo_server.c
	gcc -Wall -ansi -o ftpclient ftpclient.c

cleanest:
	rm -rf *~ core.* *# *.o p_echo_server echo_client ftpclient
